version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:10
    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
      - run:
          name: yarn install
          command: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: tests
          command: |
            mkdir -p test-results/jest
            yarn test --coverage --ci --reporters="default"  --reporters="jest-junit" --watchAll=false
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/junit.xml

      - store_artifacts:
          path: coverage
          prefix: coverage

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy:
    working_directory: ~/project
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: deploy to gh-pages
          command: |
            yarn run deploy
         
workflows:
  version: 2
  buld-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master  